apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    sas.com/component-name: sas-model-repository
    sas.com/kustomize-base: base
  name: sas-model-repository

