apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-event-stream-processing-studio-app-{{ TENANT-NAME }} #change this to the tenant name for each new tenant onboarded
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ STORAGE-CAPACITY }} #change this to desired capacity
  storageClassName: {{ STORAGE-CLASS-NAME }} #change this the desired storage class