apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-env-variables-to-esp-projects
#patch: |-
  #- op: add
    #path: /spec/projectTemplate/deployment/spec/template/spec/containers/0/env/-
    #value:
      #name: DFESP_QKB
      #value: {{ PATH-OR-VALUE }}
  #- op: add
    #path: /spec/projectTemplate/deployment/spec/template/spec/containers/0/env/-
    #value:
      #name: DFESP_QKB_LIC
      #value: {{ PATH-OR-VALUE }}
  #- op: add
    #path: /spec/projectTemplate/deployment/spec/template/spec/containers/0/env/-
    #value:
      #name: LD_LIBRARY_PATH
      #value: {{ PATH }}
target:
  group: iot.sas.com
  kind: ESPConfig
  name: sas-esp-operator
  version: v1
