
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-874f55e137f31b6d
patch: |-
  - op: add
    path: /spec/selector/matchExpressions
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-31d3c9258d0142ee
patch: |-
  - op: add
    path: /spec/template/spec/initContainers
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-a9706b13b4785391
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/command
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-63e74e1be2ea7c01
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/args
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-c613bc793eaa83ed
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/volumeDevices
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-13840789fb404880
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-a6d5a9fd6ef4ba08
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/supplementalGroups
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-696fb529d1d43e4d
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/sysctls
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-373c7294e8cd4aeb
patch: |-
  - op: add
    path: /spec/template/spec/imagePullSecrets
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-f422ed6b7fda52c8
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchFields
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-5a4f5965ceb2cddf
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/preference/matchFields
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-5a59aafd9d20060e
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/1/preference/matchFields
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-25fb492521ebed94
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAffinity/requiredDuringSchedulingIgnoredDuringExecution
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-74298ac64450875a
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAffinity/preferredDuringSchedulingIgnoredDuringExecution
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-1fce9ee739d249f0
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-71b6c98f4a4e0bac
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/namespaces
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-d996e334c1011b76
patch: |-
  - op: add
    path: /spec/template/spec/hostAliases
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-361646c2d1072180
patch: |-
  - op: add
    path: /spec/template/spec/readinessGates
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-7c0b8b75595b2140
patch: |-
  - op: add
    path: /spec/volumeClaimTemplates
    value: []
target:
  group: apps
  kind: StatefulSet
  name: sas-data-agent-server-colocated
  version: v1
