---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-config-reconciler
    sas.com/admin: namespace
  name: sas-config-reconciler
spec:
  gateways:
  - public-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /configReconciler
    - uri:
        prefix: /configReconciler/
    route:
    - destination:
        host: sas-config-reconciler
    timeout: 300s

