
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-0b66ca64b1bc431b
patch: |-
  - op: add
    path: /spec/selector/matchExpressions
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-5d5c585115d44686
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/ports
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-bf5972230c1bfbbb
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/envFrom
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-7ae0e5355dc4dff7
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/env
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-6c20713b71ca2111
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-6d6c1b619e73e236
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-2fb256add64febe8
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/command
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-18da7fcd2e8ee536
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/args
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-2d5a753818a052b3
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/ports
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-b4f2e5e1ea5e2f38
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-5c5734f9fbe40ce5
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-2506fd6bf90ea90f
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/command
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-58423e3f73e3cc7f
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/args
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-da24e98696adf89b
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-ea6dd7a6e174eba5
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/livenessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-92560eef0f450398
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/readinessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-d87d374ff8d05269
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/startupProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-1f1182b61a68131c
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-312f0209ee49b954
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/supplementalGroups
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-38daaf9a776b213b
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/sysctls
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-8c125c16dc4c8b6d
patch: |-
  - op: add
    path: /spec/template/spec/imagePullSecrets
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-defbfaf325797794
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-b62157fa1de80591
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-8e0216c0a48b3106
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/1/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-95b8b41122a7b04c
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-5af660134e632778
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/namespaces
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-2ebc63cc82ac96fe
patch: |-
  - op: add
    path: /spec/template/spec/hostAliases
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-654611dd133f561c
patch: |-
  - op: add
    path: /spec/template/spec/readinessGates
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-forecasting-data-definition
  version: v1
