---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-forecasting-filters
    sas.com/admin: namespace
  name: sas-forecasting-filters
spec:
  routes:
  - conditions:
    - prefix: /forecastingFilters
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /forecastingFilters/
    services:
    - name: sas-forecasting-filters
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /forecastingFilters/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-forecasting-filters
      port: 80
    timeoutPolicy:
      response: 300s

