---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-forecasting-events
    sas.com/admin: namespace
  name: sas-forecasting-events
spec:
  routes:
  - conditions:
    - prefix: /forecastingEvents
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /forecastingEvents/
    services:
    - name: sas-forecasting-events
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /forecastingEvents/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-forecasting-events
      port: 80
    timeoutPolicy:
      response: 300s

