---
namespace: {{ VIYA-DEPLOYMENT-NAMESPACE }}
resources:
- tenant-onboard-job.yaml

transformers:
- tenant-onboard-job-tls-transformer.yaml   # Comment out, if Viya environment is TLS disable
- ../../sas-bases/overlays/required/transformers.yaml
