apiVersion: orchestration.sas.com/v2beta10
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-esp-operator
    sas.com/component-version: 10.729.2-20231109.1699565665573
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/deploy-pre: "true"
  name: deploy-pre-esp-operator
spec:
  args:
  - name: namespace
  - name: timeout
  steps:
  - args:
    - deploy-pre-esp-operator-execute
    - --namespace
    - $namespace
    - --timeout
    - $timeout
    cmd: run
    when: (eq (.GetVariable "sas.com/sas-esp-operator-update") "true")
