apiVersion: orchestration.sas.com/v2beta15
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-redis-operator
    sas.com/component-version: 1.11.10-20231102.1698945202078
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/stop-all-execute-phase-0: "true"
  name: stop-all-execute-redis
spec:
  args:
  - name: namespace
  - default: 7200s
    name: timeout
  steps:
  - args:
    - patch
    - --namespace
    - $namespace
    - distributedredisclusters
    - $resource.Name
    - --type
    - json
    - --patch
    - '[{"op":"replace", "path": "/spec/shutdown", "value":true}]'
    cmd: kubectl
    when: (.ClusterDefinitions (((.NewClusterDefinitionsIterationSpec).WithGroup "redis.kun").WithResource "distributedredisclusters"))
    withClusterResources:
      group: redis.kun
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: distributedredisclusters
  - args:
    - wait
    - --namespace
    - $namespace
    - --for
    - delete
    - pod
    - --selector
    - managed-by=redis-cluster-operator
    - --timeout
    - $timeout
    cmd: kubectl
