apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    sas.com/component-name: sas-decisions-runtime-builder-buildkit
  name: sas-decisions-runtime-builder-buildkit
